services:
  - type: web
    name: shark-bait
    runtime: node
    rootDir: sharkbait
    plan: free
    buildCommand: npm install --omit=dev
    startCommand: npm start
    envVars:
      - key: HOST_KEY
        sync: false
